-- Shared social layer for the AI Portfolio
-- Run once in Supabase SQL Editor.

create table if not exists public.portfolio_comments (
  id bigint generated by default as identity primary key,
  work_id text not null,
  body text not null check (char_length(trim(body)) between 1 and 500),
  visitor_id text not null check (char_length(visitor_id) between 16 and 128),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists portfolio_comments_work_id_created_at_idx
  on public.portfolio_comments (work_id, created_at desc);

create table if not exists public.portfolio_likes (
  id bigint generated by default as identity primary key,
  work_id text not null,
  visitor_id text not null check (char_length(visitor_id) between 16 and 128),
  created_at timestamptz not null default timezone('utc', now()),
  unique (work_id, visitor_id)
);

create index if not exists portfolio_likes_work_id_idx
  on public.portfolio_likes (work_id);

alter table public.portfolio_comments enable row level security;
alter table public.portfolio_likes enable row level security;

drop policy if exists "Anyone can read portfolio comments" on public.portfolio_comments;
create policy "Anyone can read portfolio comments"
  on public.portfolio_comments for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can add portfolio comments" on public.portfolio_comments;
create policy "Anyone can add portfolio comments"
  on public.portfolio_comments for insert
  to anon, authenticated
  with check (
    char_length(trim(body)) between 1 and 500
    and char_length(visitor_id) between 16 and 128
  );

drop policy if exists "Anyone can read portfolio likes" on public.portfolio_likes;
create policy "Anyone can read portfolio likes"
  on public.portfolio_likes for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can add one portfolio like per visitor" on public.portfolio_likes;
create policy "Anyone can add one portfolio like per visitor"
  on public.portfolio_likes for insert
  to anon, authenticated
  with check (char_length(visitor_id) between 16 and 128);

grant usage on schema public to anon, authenticated;
grant select, insert on public.portfolio_comments to anon, authenticated;
grant select, insert on public.portfolio_likes to anon, authenticated;
grant usage, select on sequence public.portfolio_comments_id_seq to anon, authenticated;
grant usage, select on sequence public.portfolio_likes_id_seq to anon, authenticated;

-- Keep comment text and visitor identifiers private from updates/deletes:
-- no update/delete policies are created intentionally.
